server:
    port: 8080
spring:
    application:
        name: reggie_take_out
    datasource:
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.190.135/reggie?serverTimezone=UTC
            username: root
            password: root
    mvc:
        hiddenmethod:
            filter:
                enable: true
mybatis-plus:
    configuration:

        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            #???????
            id-type: ASSIGN_ID
reggie:
  path: D:\img\
